# -*- coding: utf-8 -*-
# General Education question bank for the Licensure Examination for Teachers (LET/GenEd)
# 150 questions across the standard GenEd subject areas.
# Each item: (subject, question, [options], correct_index, explanation)

QUESTIONS = [
# ---------- ENGLISH (30) ----------
("English", "Identify the part of speech of the word \"quickly\" in: \"She ran quickly.\"",
 [ "Adjective", "Adverb", "Verb", "Pronoun" ], 1,
 "\"Quickly\" modifies the verb \"ran\" and answers how, so it is an adverb."),
("English", "Choose the correct verb: \"Neither the teacher nor the students ______ present.\"",
 [ "was", "were", "is", "be" ], 1,
 "With 'neither...nor,' the verb agrees with the nearer subject, which is plural ('students'), so 'were.'"),
("English", "Which sentence is grammatically correct?",
 [ "Each of the boys have a book.", "Each of the boys has a book.", "Each of the boys are having books.", "Each of the boys were given books." ], 1,
 "\"Each\" is singular and takes the singular verb \"has.\""),
("English", "Choose the synonym of \"ubiquitous.\"",
 [ "Rare", "Omnipresent", "Tiny", "Distant" ], 1,
 "Ubiquitous means present everywhere, i.e., omnipresent."),
("English", "Choose the antonym of \"benevolent.\"",
 [ "Kind", "Generous", "Malevolent", "Gentle" ], 2,
 "Benevolent means kindly; its opposite is malevolent (wishing harm)."),
("English", "What figure of speech is used in \"The wind whispered through the trees\"?",
 [ "Simile", "Personification", "Hyperbole", "Oxymoron" ], 1,
 "Giving human characteristics (whispering) to the wind is personification."),
("English", "Which of the following is a collective noun?",
 [ "pencil", "team", "chair", "happiness" ], 1,
 "\"Team\" names a group of individuals as a single unit, so it is a collective noun."),
("English", "What is the correct plural form of \"analysis\"?",
 [ "analysises", "analysis", "analyses", "analysi" ], 2,
 "Words ending in -sis change to -ses in the plural (analysis \u2192 analyses)."),
("English", "Which sentence uses a colon correctly?",
 [ "She bought: apples, bananas, and grapes.", "She bought the following: apples, bananas, and grapes.", "The food was: delicious.", "He wanted: to go home." ], 1,
 "A colon is used after a complete statement to introduce a list."),
("English", "\"The classroom was a zoo.\" is an example of ______.",
 [ "Simile", "Metaphor", "Alliteration", "Onomatopoeia" ], 1,
 "It states the classroom IS a zoo, an implied comparison without 'like' or 'as' \u2014 a metaphor."),
("English", "The prefix \"anti-\" means ______.",
 [ "for", "against", "before", "under" ], 1,
 "Anti- means against or opposed to (e.g., anti-war, antibiotic)."),
("English", "Which word is correctly spelled?",
 [ "recieve", "receive", "receeve", "riceive" ], 1,
 "\"Receive\" follows the rule 'i before e except after c.'"),
("English", "Choose the correct pronoun: \"To ______ should I address the letter?\"",
 [ "who", "whom", "whose", "which" ], 1,
 "The pronoun is the object of the preposition 'to,' so the objective case 'whom' is correct."),
("English", "Identify the gerund in: \"Swimming is my favorite activity.\"",
 [ "favorite", "activity", "Swimming", "my" ], 2,
 "A gerund is a verb ending in -ing used as a noun; here it is the subject."),
("English", "Convert to passive voice: \"The boy ate the mango.\"",
 [ "The mango is eaten by the boy.", "The mango was eaten by the boy.", "The mango has eaten the boy.", "The mango ate the boy." ], 1,
 "The object becomes the subject and the verb becomes 'was eaten,' with the agent in a 'by' phrase."),
("English", "Which is correct?",
 [ "There were less people today.", "There were fewer people today.", "There was less people today.", "There were lesser people today." ], 1,
 "\"Fewer\" is used with countable nouns; \"less\" with mass nouns."),
("English", "Which sentence is punctuated correctly?",
 [ "The students books are on the desk.", "The student's books are on the desk.", "The students' books are on the desk.", "The students book's are on the desk." ], 2,
 "Plural possessive ending in 's' takes an apostrophe after the s: students'."),
("English", "A story written mainly to entertain is ______.",
 [ "expository", "persuasive", "narrative", "descriptive" ], 2,
 "Narrative writing tells a story and is meant to entertain."),
("English", "Which is a homophone of \"right\"?",
 [ "write", "wrote", "writ", "rite" ], 0,
 "\"Right\" and \"right\"-sounding words; among the choices, \"write\" is a homophone (also \"rite\")."),
("English", "What does the idiom \"break the ice\" mean?",
 [ "to start a conversation", "to cause trouble", "to ruin plans", "to be cold" ], 0,
 "To 'break the ice' is to ease initial awkwardness and begin a conversation."),
("English", "Which word is an abstract noun?",
 [ "table", "courage", "teacher", "city" ], 1,
 "\"Courage\" names a quality or concept, not something physical, so it is abstract."),
("English", "The main idea of a paragraph is usually found in the ______.",
 [ "topic sentence", "concluding sentence", "transitional word", "supporting detail" ], 0,
 "The topic sentence states the main idea, often at the beginning of a paragraph."),
("English", "Choose the word that is an adverb of time.",
 [ "happily", "yesterday", "huge", "quickly" ], 1,
 "Adverbs of time tell when; 'yesterday' is an adverb of time."),
("English", "Which sentence has a dangling modifier?",
 [ "Running fast, I caught the bus.", "Having finished the test, she left the room.", "Driving to Manila, the car broke down.", "Exhausted, he slept early." ], 2,
 "The car cannot drive to Manila by itself; the modifier has no clear subject."),
("English", "Identify the subject in: \"The colorful butterflies fluttered in the garden.\"",
 [ "garden", "fluttered", "butterflies", "colorful" ], 2,
 "\"Butterflies\" is the noun the sentence is about \u2014 the subject."),
("English", "Which is the predicate of \"The diligent students reviewed their lessons\"?",
 [ "The diligent students", "students", "reviewed their lessons", "their lessons" ], 2,
 "The predicate is what is said about the subject: 'reviewed their lessons.'"),
("English", "What is the connotation of the word \"home\" if it implies warmth and belonging?",
 [ "neutral", "positive", "negative", "factual" ], 1,
 "Words carry emotional associations; 'home' often carries a warm, positive connotation."),
("English", "Which is an interrogative sentence?",
 [ "Close the door.", "Where did you go?", "She sings well.", "What a lovely day!" ], 1,
 "An interrogative sentence asks a question, ending with a question mark."),
("English", "A comma is correctly used in which sentence?",
 [ "The dog barked loudly and, ran away.", "After the rain, the street shone brightly.", "She ate, rice and fish.", "He was, happy." ], 1,
 "A comma follows an introductory dependent clause ('After the rain,')."),
("English", "Choose the correct spelling.",
 [ "necessary", "neccessary", "necessery", "necesary" ], 0,
 "\"Necessary\" has one 'c' and two 's's."),

# ---------- FILIPINO (25) ----------
("Filipino", "Ano ang uring ito ng pangngalan na tumutukoy sa pangalan ng tiyak na tao, lugar, o bagay?",
 [ "Pambalana", "Pantangi", "Pamilang", "Payak" ], 1,
 "Ang pantangi ay tumutukoy sa tiyak na pangalan (isinusulat nang malaki ang unang titik)."),
("Filipino", "Ano ang kasalungat ng salitang \"masipag\"?",
 [ "masigla", "tamad", "malakas", "maayos" ], 1,
 "Ang kasalungat (antonym) ng masipag ay tamad."),
("Filipino", "Sa pangungusap na \"Ang batang lalaki ay tumatakbo,\" ano ang pang-uri?",
 [ "batang", "lalaki", "tumatakbo", "ay" ], 0,
 "Ang 'batang' ay naglalarawan sa pangngalang 'lalaki,' kaya ito ay pang-uri."),
("Filipino", "Ano ang tawag sa salitang sumasagot sa tanong na \"paano\" o \"kailan\" para sa pandiwa?",
 [ "pang-abay", "pang-uri", "pangngalan", "panghalip" ], 0,
 "Ang pang-abay ay naglalarawan sa pandiwa/panaguri."),
("Filipino", "Kilala bilang \"Ama ng Panitikang Tagalog\" na sumulat ng Noli Me Tangere?",
 [ "Jose Rizal", "Francisco Balagtas", "Andres Bonifacio", "Emilio Jacinto" ], 1,
 "Si Francisco Balagtas (Balagtas) ang itinuturing na Ama ng Panitikang Tagalog."),
("Filipino", "Anong uri ng akda ang \"Ibong Adarna\"?",
 [ "Epiko", "Awit", "Korido", "Sanaysay" ], 2,
 "Ang Ibong Adarna ay isang korido (may sukat at tugma sa 8 pantig)."),
("Filipino", "Ano ang kahulugan ng \"Noli Me Tangere\" ayon sa salin?",
 [ "Huwag mo akong salingin", "Huwag mo akong hawakan", "Huwag mo akong saktan", "Huwag mo akong kalimutan" ], 1,
 "Ang Noli Me Tangere ay nangangahulugang 'Huwag mo akong hawakan/salingin' (Touch Me Not)."),
("Filipino", "Alin ang wastong baybay ng salita?",
 [ "kumustahin", "kumusta-hin", "kumustahin", "kumustáhin" ], 0,
 "Ang wastong baybay ng pandiwa ay 'kumustahin.'"),
("Filipino", "Ano ang panghalip na pamatlig ng \"ito\" sa maramihan?",
 [ "dito", "ito", "mga ito", "iyan" ], 2,
 "Ang pamatlig na 'ito' sa maramihan ay 'mga ito.'"),
("Filipino", "Sino ang sumulat ng \"Florante at Laura\"?",
 [ "Jose Rizal", "Francisco Balagtas", "Claro M. Recto", "Lope K. Santos" ], 1,
 "Ang Florante at Laura ay isinulat ni Francisco Balagtas."),
("Filipino", "Ano ang tawag sa elemento ng maikling kuwento na tumutukoy sa pagkakasunod-sunod ng mga pangyayari?",
 [ "Tagpuan", "Banghay", "Tauhan", "Tema" ], 1,
 "Ang banghay o balangkas ay ang pagkakasunod-sunod ng mga pangyayari sa isang kuwento."),
("Filipino", "Anong panahunan ng pandiwa ang \"kumakain\"?",
 [ "Nagaganap", "Naganap", "Magaganap", "Pangkasalukuyan" ], 0,
 "Ang salitang-ugat na may reduplikasyon sa gitna (kumakain) ay panahong nagaganap."),
("Filipino", "Ibig sabihin ng idyomang \"nagtaingang-kawali\"?",
 [ "Nagulat", "Nagmagandang-loob", "Naging bingi/nagkunwaring hindi narinig", "Nagpakabait" ], 2,
 "Ang 'nagtaingang-kawali' ay nangangahulugang nagkunwaring walang narinig."),
("Filipino", "Sa \"Mahal kita,\" ano ang tuwirang layon?",
 [ "Mahal", "kita", "ako", "tayo" ], 1,
 "Sa 'Mahal kita,' ang 'kita' ay panghalip na bumubuo ng tuwirang layon."),
("Filipino", "Anong uri ng pangungusap ang \"Halika na!\"?",
 [ "Padamdam", "Pasaklaw", "Pakiusap", "Patanong" ], 2,
 "Ang pakiusap ay humihingi o nag-uutos nang mahinahon; 'Halika na!' ay pakiusap."),
("Filipino", "Ano ang tawag sa pinakamaliit na yunit ng tunog sa isang salita?",
 [ "Ponema", "Pantomino", "Pantig", "Pangungusap" ], 0,
 "Ang ponema ang pinakamaliit na yunit ng tunog na nagbabago ng kahulugan."),
("Filipino", "Ibig sabihin ng \"bihasa\"?",
 [ "bago", "sanay", "tamad", "marunong" ], 1,
 "Ang 'bihasa' ay nangangahulugang sanay o eksperto sa isang gawain."),
("Filipino", "Sino ang itinuturing na \"Pambansang Bayani\" ng Pilipinas?",
 [ "Andres Bonifacio", "Jose Rizal", "Emilio Aguinaldo", "Antonio Luna" ], 1,
 "Si Jose Rizal ang itinuturing na pambansang bayani ng Pilipinas."),
("Filipino", "Alin ang tamang tamabay (spacing/baybay) ng \"barangay\"?",
 [ "barangay", "bahargay", "barangai", "baranghi" ], 0,
 "Ang wastong baybay ay 'barangay.'"),
("Filipino", "Anong uri ng akdang pampanitikan ang naglalahad ng mga kaisipan tungkol sa lipunan?",
 [ "Talumpati", "Sanaysay", "Tula", "Awit" ], 1,
 "Ang sanaysay ay akda na naglalahad ng mga pananaw o kaisipan."),
("Filipino", "Ibig sabihin ng \"malawak\" sa konteksto ng \"malawak ang kaniyang pang-unawa\"?",
 [ "mababa", "maliit", "marami at masagana", "makipot" ], 2,
 "Sa konteksto ng pag-iisip, ang 'malawak' ay tumutukoy sa masagana o malalim na pang-unawa."),
("Filipino", "Anong taon inilimbag ang unang edisyon ng \"Noli Me Tangere\"?",
 [ "1878", "1887", "1896", "1900" ], 1,
 "Inilimbag ang Noli Me Tangere noong 1887 sa Berlin, Alemanya."),
("Filipino", "Ano ang simuno sa pangungusap na \"Ang mga mag-aaral ay nag-review\"?",
 [ "mga mag-aaral", "nag-review", "ay", "Ang" ], 0,
 "Ang 'Ang mga mag-aaral' ang paksa o simuno ng pangungusap."),
("Filipino", "Ano ang kasingkahulugan ng \"kisame\"?",
 [ "sahig", "dingding", "bubong", "pintuan" ], 2,
 "Ang kisame ay ang panloob na bubong; kasingkahulugan nito ang 'bubong.'"),
("Filipino", "Sa tula, ano ang tawag sa bilang ng pantig sa bawat taludtod?",
 [ "Tugma", "Sukat", "Talinghaga", "Indayog" ], 1,
 "Ang sukat ay ang bilang ng pantig sa bawat taludtod ng tula."),

# ---------- MATHEMATICS (25) ----------
("Mathematics", "What is 15% of 200?",
 [ "20", "30", "35", "40" ], 1,
 "0.15 \u00d7 200 = 30."),
("Mathematics", "Solve: 3(x \u2212 4) = 21.",
 [ "x = 3", "x = 9", "x = 11", "x = 17" ], 2,
 "3x \u2212 12 = 21 \u2192 3x = 33 \u2192 x = 11."),
("Mathematics", "What is the value of 2\u00b3 + 4\u00b2?",
 [ "16", "24", "32", "14" ], 1,
 "8 + 16 = 24."),
("Mathematics", "What is the sum of the measures of the interior angles of a triangle?",
 [ "90\u00b0", "180\u00b0", "270\u00b0", "360\u00b0" ], 1,
 "The interior angles of any triangle sum to 180\u00b0."),
("Mathematics", "Simplify: 5/8 \u00f7 5/4.",
 [ "1/2", "2/1", "1/4", "5/2" ], 0,
 "5/8 \u00d7 4/5 = 20/40 = 1/2."),
("Mathematics", "What is the area of a rectangle with length 12 cm and width 5 cm?",
 [ "17 cm\u00b2", "30 cm\u00b2", "60 cm\u00b2", "120 cm\u00b2" ], 2,
 "Area = length \u00d7 width = 12 \u00d7 5 = 60 cm\u00b2."),
("Mathematics", "Which is the greatest common factor (GCF) of 12 and 18?",
 [ "2", "3", "6", "9" ], 2,
 "The largest number dividing both 12 and 18 is 6."),
("Mathematics", "If a number is divided by 3 and the result is 15, choose the correct equation.",
 [ "x/3 = 15", "3x = 15", "x + 3 = 15", "x \u2212 3 = 15" ], 0,
 "\"A number divided by 3\" is x/3, equal to 15."),
("Mathematics", "What is the perimeter of a square with side length 7 m?",
 [ "14 m", "28 m", "49 m", "35 m" ], 1,
 "Perimeter = 4 \u00d7 side = 4 \u00d7 7 = 28 m."),
("Mathematics", "Convert 0.75 to a fraction in lowest terms.",
 [ "3/4", "75/100", "7/5", "1/4" ], 0,
 "0.75 = 75/100 = 3/4."),
("Mathematics", "What is the product of 8 and 12?",
 [ "20", "84", "96", "108" ], 2,
 "8 \u00d7 12 = 96."),
("Mathematics", "Solve for x: 2x + 5 = 17.",
 [ "x = 4", "x = 6", "x = 11", "x = 22" ], 1,
 "2x = 12 \u2192 x = 6."),
("Mathematics", "What is the mean of the numbers 4, 8, 12, 16?",
 [ "8", "10", "12", "16" ], 1,
 "(4+8+12+16)/4 = 40/4 = 10."),
("Mathematics", "What is 50% of 80?",
 [ "20", "30", "40", "50" ], 2,
 "0.50 \u00d7 80 = 40."),
("Mathematics", "Which is the least common multiple (LCM) of 4 and 6?",
 [ "10", "12", "24", "8" ], 1,
 "The smallest number divisible by both 4 and 6 is 12."),
("Mathematics", "A triangle has angles 50\u00b0 and 60\u00b0. What is the third angle?",
 [ "50\u00b0", "60\u00b0", "70\u00b0", "80\u00b0" ], 2,
 "180\u00b0 \u2212 (50+60) = 70\u00b0."),
("Mathematics", "What is \u221a144?",
 [ "10", "11", "12", "14" ], 2,
 "12 \u00d7 12 = 144, so the square root of 144 is 12."),
("Mathematics", "Simplify: \u22123 + (\u22124).",
 [ "7", "\u22127", "\u22121", "1" ], 1,
 "Adding two negatives: \u22123 + (\u22124) = \u22127."),
("Mathematics", "What is the value of 10\u00b3?",
 [ "100", "1000", "10000", "30" ], 1,
 "10\u00b3 = 10 \u00d7 10 \u00d7 10 = 1000."),
("Mathematics", "What is the distance around a circle called?",
 [ "Area", "Diameter", "Circumference", "Radius" ], 2,
 "The distance around a circle is its circumference."),
("Mathematics", "What is 3/4 of 40?",
 [ "20", "25", "30", "35" ], 2,
 "(3/4) \u00d7 40 = 30."),
("Mathematics", "A shirt costs 250 pesos and is on a 20% discount. What is the new price?",
 [ "50 pesos", "200 pesos", "210 pesos", "230 pesos" ], 1,
 "Discount = 0.20 \u00d7 250 = 50; new price = 250 \u2212 50 = 200."),
("Mathematics", "What is the value of 4! (4 factorial)?",
 [ "12", "16", "24", "48" ], 2,
 "4! = 4 \u00d7 3 \u00d7 2 \u00d7 1 = 24."),
("Mathematics", "Which of these is a prime number?",
 [ "21", "29", "33", "39" ], 1,
 "29 has no divisors other than 1 and itself, so it is prime."),
("Mathematics", "What is 2.5\u00d75?",
 [ "10.5", "12.0", "12.5", "125" ], 2,
 "2.5 \u00d7 5 = 12.5."),

# ---------- SCIENCE (35) ----------
("Science", "Which organelle is called the powerhouse of the cell?",
 [ "Nucleus", "Mitochondrion", "Ribosome", "Golgi body" ], 1,
 "Mitochondria produce ATP, the cell's energy, hence 'powerhouse.'"),
("Science", "What is the chemical symbol for water?",
 [ "HO", "H2O", "O2", "H2" ], 1,
 "Water is composed of two hydrogen atoms and one oxygen atom: H\u2082O."),
("Science", "Which planet is known as the Red Planet?",
 [ "Venus", "Mars", "Jupiter", "Saturn" ], 1,
 "Mars appears red because of iron oxide (rust) on its surface."),
("Science", "What is the process by which plants make food using sunlight?",
 [ "Respiration", "Photosynthesis", "Transpiration", "Fermentation" ], 1,
 "Plants convert light, water, and CO\u2082 into glucose via photosynthesis."),
("Science", "What is the basic unit of life?",
 [ "Atom", "Cell", "Tissue", "Organ" ], 1,
 "The cell is the smallest basic unit that can carry out all life processes."),
("Science", "Which force pulls objects toward the center of the Earth?",
 [ "Friction", "Magnetism", "Gravity", "Tension" ], 2,
 "Gravity attracts objects toward the center of the Earth."),
("Science", "What is the boiling point of water in Celsius at sea level?",
 [ "90\u00b0C", "100\u00b0C", "110\u00b0C", "120\u00b0C" ], 1,
 "At standard atmospheric pressure, water boils at 100\u00b0C."),
("Science", "Which organ pumps blood around the body?",
 [ "Liver", "Lungs", "Heart", "Kidney" ], 2,
 "The heart is a muscular pump that circulates blood."),
("Science", "What gas do humans inhale that is essential for respiration?",
 [ "Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen" ], 1,
 "Oxygen is required for cellular respiration in the human body."),
("Science", "Which of the following is a renewable source of energy?",
 [ "Coal", "Oil", "Solar", "Natural gas" ], 2,
 "Solar energy is replenished naturally, making it renewable."),
("Science", "What is the process of changing water into vapor called?",
 [ "Condensation", "Evaporation", "Sublimation", "Freezing" ], 1,
 "Evaporation is the change of a liquid to a gas (vapor)."),
("Science", "Which part of the plant absorbs water and minerals from the soil?",
 [ "Leaves", "Stem", "Roots", "Flowers" ], 2,
 "Roots absorb water and dissolved minerals from the soil."),
("Science", "What is the chemical formula for table salt?",
 [ "NaCl", "KCl", "H2O", "CO2" ], 0,
 "Table salt is sodium chloride, NaCl."),
("Science", "What is the largest planet in the Solar System?",
 [ "Earth", "Jupiter", "Saturn", "Neptune" ], 1,
 "Jupiter is the largest planet in our Solar System."),
("Science", "Which blood cells help fight infection?",
 [ "Red blood cells", "White blood cells", "Platelets", "Plasma" ], 1,
 "White blood cells (leukocytes) are part of the immune system."),
("Science", "What is the process of plants losing water vapor through their leaves?",
 [ "Photosynthesis", "Respiration", "Transpiration", "Digestion" ], 2,
 "Transpiration is the loss of water vapor through stomata in leaves."),
("Science", "Which type of rock is formed from cooled magma or lava?",
 [ "Sedimentary", "Igneous", "Metamorphic", "Fossil" ], 1,
 "Igneous rock forms from the cooling and solidification of magma/lava."),
("Science", "What is the SI unit of length?",
 [ "Gram", "Meter", "Liter", "Second" ], 1,
 "The meter is the SI base unit of length."),
("Science", "Which organelle contains the genetic material (DNA) of a eukaryotic cell?",
 [ "Nucleus", "Mitochondrion", "Chloroplast", "Ribosome" ], 0,
 "The nucleus houses the cell's DNA."),
("Science", "What is the term for an animal that eats only plants?",
 [ "Carnivore", "Herbivore", "Omnivore", "Insectivore" ], 1,
 "A herbivore feeds mainly on plants."),
("Science", "Which of these is a vector quantity because it has both magnitude and direction?",
 [ "Mass", "Speed", "Velocity", "Time" ], 2,
 "Velocity includes direction, so it is a vector quantity."),
("Science", "What is the most abundant element in the Earth's atmosphere?",
 [ "Oxygen", "Nitrogen", "Carbon dioxide", "Argon" ], 1,
 "Nitrogen makes up about 78% of the atmosphere."),
("Science", "What instrument is used to measure temperature?",
 [ "Barometer", "Thermometer", "Hygrometer", "Anemometer" ], 1,
 "A thermometer measures temperature."),
("Science", "Which system is responsible for breathing in humans?",
 [ "Digestive", "Circulatory", "Respiratory", "Nervous" ], 2,
 "The respiratory system handles gas exchange (breathing)."),
("Science", "What is the process of a liquid changing into a solid called?",
 [ "Melting", "Freezing", "Boiling", "Sublimation" ], 1,
 "Freezing is the change from liquid to solid."),
("Science", "Which is the largest internal organ of the human body?",
 [ "Heart", "Brain", "Liver", "Lungs" ], 2,
 "The liver is the largest internal organ in the human body."),
("Science", "What causes the phases of the Moon?",
 [ "Earth's rotation", "Moon's orbit around Earth", "Sun's rays on Earth", "Earth's tilt" ], 1,
 "As the Moon orbits Earth, different portions of its illuminated side are visible."),
("Science", "What is the chemical symbol for gold?",
 [ "Go", "Gd", "Au", "Ag" ], 2,
 "Au is the symbol for gold, from the Latin 'aurum.'"),
("Science", "Which vitamin is produced by the skin when exposed to sunlight?",
 [ "Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D" ], 3,
 "Sunlight enables the skin to synthesize vitamin D."),
("Science", "What is the smallest unit of a chemical element that retains its properties?",
 [ "Molecule", "Atom", "Compound", "Mixture" ], 1,
 "The atom is the smallest unit of an element retaining its properties."),
("Science", "In a food chain, which are the producers?",
 [ "Carnivores", "Herbivores", "Plants", "Fungi" ], 2,
 "Plants (and some algae) produce their own food, so they are producers."),
("Science", "What is sound produced by?",
 [ "Light", "Vibration", "Heat", "Pressure" ], 1,
 "Sound is produced by vibrations that travel as waves."),
("Science", "Which is the closest planet to the Sun?",
 [ "Earth", "Venus", "Mercury", "Mars" ], 2,
 "Mercury is the planet closest to the Sun."),
("Science", "What is the pH of a neutral solution?",
 [ "0", "7", "14", "5" ], 1,
 "A pH of 7 is neutral (e.g., pure water)."),
("Science", "Which blood component helps blood to clot?",
 [ "Red blood cells", "White blood cells", "Platelets", "Serum" ], 2,
 "Platelets stick together to form clots and stop bleeding."),

# ---------- SOCIAL SCIENCE (35) ----------
("Social Science", "Who is known as the first President of the Philippines?",
 [ "Jose Rizal", "Emilio Aguinaldo", "Manuel Quezon", "Andres Bonifacio" ], 1,
 "Emilio Aguinaldo became the first President of the Philippine Republic in 1899."),
("Social Science", "How many continents are there on Earth?",
 [ "5", "6", "7", "8" ], 2,
 "There are seven continents: Africa, Antarctica, Asia, Europe, North America, Oceania, South America."),
("Social Science", "Which branch of the Philippine government makes laws?",
 [ "Executive", "Legislative", "Judicial", "Barangay" ], 1,
 "The Legislative branch (Congress) makes and passes laws."),
("Social Science", "What is the capital city of the Philippines?",
 [ "Quezon City", "Manila", "Cebu", "Davao" ], 1,
 "Manila is the capital of the Philippines."),
("Social Science", "What is the basic unit of currency in the Philippines?",
 [ "Dollar", "Peso", "Yen", "Euro" ], 1,
 "The Philippine peso is the country's currency."),
("Social Science", "The document that states the rights and duties of citizens is the ______.",
 [ "Constitution", "Treaty", "Charter", "Manifesto" ], 0,
 "The Constitution is the supreme law that defines rights and the structure of government."),
("Social Science", "Who wrote the Declaration of Philippine Independence in 1898?",
 [ "Jose Rizal", "Emilio Aguinaldo", "Andres Bonifacio", "Ramon Magsaysay" ], 1,
 "Aguinaldo proclaimed Philippine independence on June 12, 1898."),
("Social Science", "Which is the largest island in the Philippines by area?",
 [ "Luzon", "Mindanao", "Visayas", "Palawan" ], 0,
 "Luzon is the largest island in the Philippines in both area and population."),
("Social Science", "What is the study of the production, distribution, and consumption of goods and services?",
 [ "History", "Economics", "Geography", "Sociology" ], 1,
 "Economics studies how societies allocate scarce resources."),
("Social Science", "Which Philippine region borders the waters of the South China Sea on the west?",
 [ "Mindanao", "Luzon", "Visayas", "Bicol" ], 1,
 "Luzon lies along the western seaboard fronting the South China Sea (West Philippine Sea)."),
("Social Science", "The principle that all Filipinos are equal before the law is guaranteed by ______.",
 [ "Due process", "Equal protection", "Habeas corpus", "Writ of amparo" ], 1,
 "The equal protection clause ensures that all persons under the law are treated the same."),
("Social Science", "Which international organization aims to promote world peace and security?",
 [ "UN", "ASEAN", "EU", "NATO" ], 0,
 "The United Nations (UN) promotes international peace and cooperation."),
("Social Science", "What is the term for the movement of people from rural to urban areas?",
 [ "Urbanization", "Industrialization", "Globalization", "Migration" ], 0,
 "Urbanization is the shift of populations from rural to urban centers."),
("Social Science", "Who is the chief executive of a province?",
 [ "Mayor", "Governor", "Senator", "Judge" ], 1,
 "Each province is headed by a provincial governor."),
("Social Science", "The 1987 Philippine Constitution has how many articles?",
 [ "14", "16", "18", "20" ], 2,
 "The 1987 Constitution contains 18 articles."),
("Social Science", "Which statement about volcanoes is correct regarding the Philippine archipelago?",
 [ "Philippines has no active volcanoes", "The Philippines lies inside the Pacific Ring of Fire", "Volcanoes are all dormant", "Mt. Pinatubo is in Mindanao" ], 1,
 "The Philippines is part of the Pacific Ring of Fire, hence its many active volcanoes."),
("Social Science", "What is the highest peak in the Philippines?",
 [ "Mt. Pulag", "Mt. Apo", "Mt. Pinatubo", "Mt. Makiling" ], 1,
 "Mt. Apo in Davao is the highest mountain in the Philippines."),
("Social Science", "Which body of water separates the Philippines from Taiwan?",
 [ "Bashi Channel", "Celebes Sea", "Sulu Sea", "Mindoro Strait" ], 0,
 "The Bashi Channel lies between Taiwan and the Philippines."),
("Social Science", "The study of past events is called ______.",
 [ "Geography", "History", "Anthropology", "Archaeology" ], 1,
 "History is the study of past events and their records."),
("Social Science", "What is the smallest local government unit in the Philippines?",
 [ "Province", "City", "Municipality", "Barangay" ], 3,
 "The barangay is the smallest political unit under the Local Government Code."),
("Social Science", "ASEAN stands for ______.",
 [ "Association of Southeast Asian Nations", "Alliance of South East Asia Nations", "Association of South East Asian Network", "Alliance of Sovereign East Asian Nations" ], 0,
 "ASEAN is the Association of Southeast Asian Nations."),
("Social Science", "The President serves as the head of which branch of the Philippine government?",
 [ "Legislative", "Executive", "Judicial", "Judiciary" ], 1,
 "The President heads the Executive branch of government."),
("Social Science", "Which of these is the most populous country in the world?",
 [ "China", "India", "United States", "Indonesia" ], 1,
 "India is currently the world's most populous country."),
("Social Science", "What is the term for the money collected by the government from citizens to fund public services?",
 [ "Budget", "Tax", "Loan", "Subsidy" ], 1,
 "Taxes are mandatory contributions used to fund government services."),
("Social Science", "President Corazon Aquino, the first woman president of the Philippines, took office in ______.",
 [ "1965", "1972", "1986", "1992" ], 2,
 "Corazon Aquino became president after the 1986 EDSA People Power Revolution."),
("Social Science", "Which continent is known as the birthplace of democracy (ancient Greece)?",
 [ "Africa", "Europe", "Asia", "Australia" ], 1,
 "Ancient Greece, in Europe, is credited as democracy's birthplace."),
("Social Science", "What does the term \"GDP\" stand for?",
 [ "Global Domestic Product", "Gross Domestic Product", "General Development Plan", "Gross Development Program" ], 1,
 "GDP is the total value of goods and services produced in a country."),
("Social Science", "Which document recognized human rights for all people within a nation?",
 [ "UN Charter", "Universal Declaration of Human Rights", "Geneva Convention", "Magna Carta" ], 1,
 "The UDHR sets the fundamental rights of all human beings."),
("Social Science", "The tropical climate of the Philippines is affected by ______.",
 [ "the equator and monsoon winds", "the poles", "the desert region", "the polar jet stream" ], 0,
 "Its proximity to the equator and monsoon winds shape its tropical climate."),
("Social Science", "Who is known as the \"Great Plebeian\" and founder of the Katipunan?",
 [ "Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Lapu-Lapu" ], 1,
 "Bonifacio founded the Katipunan to fight for Philippine independence."),
("Social Science", "Which is the national language of the Philippines?",
 [ "English", "Filipino", "Cebuano", "Ilocano" ], 1,
 "Filipino is the national language of the Philippines."),
("Social Science", "Which government agency is responsible for processing taxes in the Philippines?",
 [ "BIR", "BSP", "DOLE", "DTI" ], 0,
 "The Bureau of Internal Revenue (BIR) collects national taxes."),
("Social Science", "The Great Wall, the Forbidden City, and the Terracotta Army belong to which country?",
 [ "Japan", "China", "India", "Thailand" ], 1,
 "These landmarks are found in China."),
("Social Science", "What term describes the exchange of goods and services between countries?",
 [ "Trade", "Tourism", "Taxation", "Production" ], 0,
 "International trade is the exchange of goods/services across borders."),
("Social Science", "The 1986 peaceful revolution that restored democracy in the Philippines is called ______.",
 [ "EDSA People Power Revolution", "Philippine Revolution", "Martial Law", "War on Drugs" ], 0,
 "The EDSA People Power Revolution in February 1986 peacefully ended the Marcos regime."),
]
